config/routes.rb
Rails.application.routes.draw do


  # get 'image/new'
  # get 'image/create'
  # get 'image/destroy'
  # post 'image/create'


  root 'albums#index'
  get 'images/new'

  resources :albums do
    resources :images
  end

  post '/album/:id/images/:id' , to: 'image#new'
  post '/album/1/image' , to: 'image#new'
  post '/image' , to: 'image#new'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  has_many(:images)

  def add_image(image_url)
    images.push(Image.create(image_url:image_url))

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy]

  def index
    @albums = Album.all
  end

  def new
    @album = Album.new
  end

  def show
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /images/1/edit
  def edit
  end


  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /albums or /albums.json
  def image
    @album.add_image(image_url)
    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_album
    @album = Album.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def album_params
    params.require(:album).permit(
      :name, :images,image_attributes: [:id,:images_url])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/image_controller.rb
class ImageController < ApplicationController

  # GET /images/1/edit
  def edit
  end

  # PATCH/PUT /images/1 or /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: "Image was successfully updated." }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @album = Album.find(params[:album_id])
    Image.create(image_url: params[:q],album_id:params[:album_id])
    redirect_to @album, notice: "Image was successfully updated."
  end

  def create
    @album = Album.find(params[:album_id])
    @image = @album.images.build(params[:image])
    @image.save
  end

  def destroy
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_image
    @image = Image.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def image_params
    params.require(:image_url)
  end


end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>



<%= link_to 'Show', @album %> |

<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Albums</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Images</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.name %></td>
        <td><%= link_to 'Show' , album%></td>
        <td><%= link_to 'Change Name' ,edit_album_path(album)%></td>
        <td><%= link_to 'Destroy',album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<div>
<%= render 'form', album: @album %>
</div>

<br>
<div>
<%= link_to 'Back', albums_path %>
</div>

app/views/albums/show.html.erb
<h1>Album Details</h1>

<h2>Album Name -
  <%= @album.name %>
</h2>


<h3>Album Images -
  <table>
    <tbody>
      <tr>
        <% @album.images.each do |img| %>
          <td><img src="<%=img.image_url%>" width="200" height="200" /></td>
        <% end %>
    </tr>
    </tbody>
  </table>

</h3>


<%#= button_tag "Save Changes", :onclick => @album.add_image("https://i.pinimg.com/564x/46/da/e5/46dae512e375bee2664a025507da8795.jpg")%>

<%= form_tag("/image", method: "post") do %>
  <%= hidden_field_tag(:album_id, @album.id) %>
  <%= label_tag(:q, "add image:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("submit") %>
<% end %>

<!--<<%#= form_with(model: @image) do |form| %>-->

<!--  <div class="field">-->
<!--    <p>Add Image</p>-->
    <%#= form.text_field :image_url %>
<!--  </div>-->
<!--  <br>-->
<!--  <div class="actions">-->
    <%#= form.submit %>
<!--  </div>-->
<!--<%# end %>>-->


<%#= render 'image/new',album: @album  %>

<%= link_to 'Back', albums_path %>

app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>

app/views/image/_form.html.erb
<%= form_with(model: image) do |form| %>

  <div class="field">
    <%= form.text_field :image_url %>
  </div>
<br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/image/create.html.erb
<h1>Image#create</h1>
<p>Find me in app/views/image/create.html.erb</p>

app/views/image/destroy.html.erb
<h1>Image#destroy</h1>
<p>Find me in app/views/image/destroy.html.erb</p>

app/views/image/new.html.erb
<h1>New Image</h1>

<div>
  <%= render 'form', album: @album %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>